### ISSUE TITLE
Again, another missing module

### ISSUE THREAD

**Issue by xray1111** [sieve-microservices/rca-evaluation#2]
This 'metric_str_utils' module seems to be a local python file but was not submit, both cluster.py and granger_causality.py fail on importing it.

**Comment by adamiaonr** [comment]
Hi,

I'll take a look at it and update it asap (probably by tomorrow).

Thanks for reporting it.

**Comment by adamiaonr** [comment]
For some reason, cluster.py and granger_causality.py had an import with the wrong name.

Fixed.
